<?php

return [
    'internal_secret' => env('ACL_INTERNAL_SECRET'),

    'permissions' => [
        ['id' => 'dashboard:visualizar', 'label' => 'Visualizar dashboard', 'group' => 'Dashboard'],
        ['id' => 'campanhas:gerenciar', 'label' => 'Gerenciar campanhas', 'group' => 'Campanhas'],
        ['id' => 'campanhas:visualizar', 'label' => 'Visualizar campanhas', 'group' => 'Campanhas'],
        ['id' => 'campanhas:executar', 'label' => 'Executar campanhas', 'group' => 'Campanhas'],
        ['id' => 'usuarios:gerenciar', 'label' => 'Gerenciar usuários', 'group' => 'Usuários'],
        ['id' => 'usuarios:visualizar', 'label' => 'Visualizar usuários', 'group' => 'Usuários'],
        ['id' => 'parceiros:gerenciar', 'label' => 'Gerenciar parceiros', 'group' => 'Parceiros'],
        ['id' => 'parceiros:visualizar', 'label' => 'Visualizar parceiros', 'group' => 'Parceiros'],
        ['id' => 'locais:gerenciar', 'label' => 'Gerenciar locais', 'group' => 'Locais'],
        ['id' => 'locais:visualizar', 'label' => 'Visualizar locais', 'group' => 'Locais'],
        ['id' => 'regioes:gerenciar', 'label' => 'Gerenciar regiões', 'group' => 'Regiões'],
        ['id' => 'regioes:visualizar', 'label' => 'Visualizar regiões', 'group' => 'Regiões'],
        ['id' => 'relatorios:visualizar', 'label' => 'Visualizar relatórios', 'group' => 'Relatórios'],
        ['id' => 'relatorios:exportar', 'label' => 'Exportar relatórios', 'group' => 'Relatórios'],
        ['id' => 'tre:consultar', 'label' => 'Consultar TRE', 'group' => 'TRE'],
        ['id' => 'permissoes:gerenciar', 'label' => 'Gerenciar permissões', 'group' => 'Permissões'],
        ['id' => 'perfil:visualizar', 'label' => 'Visualizar perfil', 'group' => 'Perfil'],
    ],

    'roles' => [
        'role-admin' => [
            'name' => 'Administrador',
            'description' => 'Acesso total ao sistema de campanha',
            'permissions' => [
                'dashboard:visualizar',
                'usuarios:gerenciar',
                'usuarios:visualizar',
                'permissoes:gerenciar',
                'parceiros:gerenciar',
                'parceiros:visualizar',
                'locais:gerenciar',
                'locais:visualizar',
                'regioes:gerenciar',
                'regioes:visualizar',
                'relatorios:visualizar',
                'relatorios:exportar',
                'tre:consultar',
                'campanhas:gerenciar',
                'campanhas:visualizar',
                'campanhas:executar',
                'perfil:visualizar',
            ],
        ],
        'role-coordenador' => [
            'name' => 'Coordenador Regional',
            'description' => 'Gerencia equipe e atividades em sua região',
            'permissions' => [
                'dashboard:visualizar',
                'parceiros:visualizar',
                'locais:gerenciar',
                'locais:visualizar',
                'regioes:visualizar',
                'relatorios:visualizar',
                'tre:consultar',
                'campanhas:gerenciar',
                'campanhas:visualizar',
                'perfil:visualizar',
            ],
        ],
        'role-agente' => [
            'name' => 'Agente de Campo',
            'description' => 'Executa atividades e registra apoiadores',
            'permissions' => [
                'dashboard:visualizar',
                'locais:visualizar',
                'campanhas:visualizar',
                'campanhas:executar',
                'perfil:visualizar',
            ],
        ],
        'role-analista' => [
            'name' => 'Analista',
            'description' => 'Acesso a relatórios e consultas TRE',
            'permissions' => [
                'dashboard:visualizar',
                'relatorios:visualizar',
                'relatorios:exportar',
                'tre:consultar',
                'campanhas:visualizar',
                'perfil:visualizar',
            ],
        ],
        'role-suporte-n1' => [
            'name' => 'Suporte N1',
            'description' => 'Acesso padrão de suporte: visualização operacional e execução básica.',
            'permissions' => [
                'dashboard:visualizar',
                'campanhas:visualizar',
                'campanhas:executar',
                'locais:visualizar',
                'perfil:visualizar',
            ],
        ],
        'role-suporte-n2' => [
            'name' => 'Suporte N2',
            'description' => 'Acesso avançado de suporte: operação, cadastros e inteligência sem administração total de permissões.',
            'permissions' => [
                'dashboard:visualizar',
                'campanhas:gerenciar',
                'campanhas:visualizar',
                'campanhas:executar',
                'usuarios:visualizar',
                'parceiros:gerenciar',
                'parceiros:visualizar',
                'locais:gerenciar',
                'locais:visualizar',
                'regioes:gerenciar',
                'regioes:visualizar',
                'relatorios:visualizar',
                'relatorios:exportar',
                'tre:consultar',
                'perfil:visualizar',
            ],
        ],
        'role-suporte-n3' => [
            'name' => 'Suporte N3',
            'description' => 'Acesso total de suporte ao sistema.',
            'permissions' => [
                'dashboard:visualizar',
                'usuarios:gerenciar',
                'usuarios:visualizar',
                'permissoes:gerenciar',
                'parceiros:gerenciar',
                'parceiros:visualizar',
                'locais:gerenciar',
                'locais:visualizar',
                'regioes:gerenciar',
                'regioes:visualizar',
                'relatorios:visualizar',
                'relatorios:exportar',
                'tre:consultar',
                'campanhas:gerenciar',
                'campanhas:visualizar',
                'campanhas:executar',
                'perfil:visualizar',
            ],
        ],
    ],
];
